name: Build Executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # allows you to trigger it manually from GitHub's website

jobs:

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-activate-base: false
          activate-environment: cookie

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install -c conda-forge cadquery -y
          pip install opencv-python scikit-image scipy shapely pyinstaller

      - name: Build .exe
        shell: bash -el {0}
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            --name CookieCutterGenerator \
            --collect-all cadquery \
            --collect-all OCC \
            --collect-all cadquery_occ \
            --hidden-import skimage.morphology \
            --hidden-import skimage.filters \
            --hidden-import skimage.util \
            --hidden-import scipy.interpolate \
            --hidden-import scipy.spatial.distance \
            --hidden-import shapely \
            --hidden-import shapely.geometry \
            --hidden-import shapely.ops \
            main.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: CookieCutterGenerator-Windows
          path: dist/CookieCutterGenerator.exe


  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: "3.10"
          auto-activate-base: false
          activate-environment: cookie

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda install -c conda-forge cadquery -y
          pip install opencv-python scikit-image scipy shapely pyinstaller

      - name: Build Mac binary
        shell: bash -el {0}
        run: |
          pyinstaller \
            --onefile \
            --windowed \
            --name CookieCutterGenerator \
            --collect-all cadquery \
            --collect-all OCC \
            --collect-all cadquery_occ \
            --hidden-import skimage.morphology \
            --hidden-import skimage.filters \
            --hidden-import skimage.util \
            --hidden-import scipy.interpolate \
            --hidden-import scipy.spatial.distance \
            --hidden-import shapely \
            --hidden-import shapely.geometry \
            --hidden-import shapely.ops \
            main.py

      - name: Upload Mac executable
        uses: actions/upload-artifact@v4
        with:
          name: CookieCutterGenerator-Mac
          path: dist/CookieCutterGenerator
